# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eddfb099e5f1cd03ed879e47af593de6f147374315a95e76c6822c14faa62117409be35cecda39c55234286382f88364c7962d4cca1b138a232d348fade4c8c

test:
  secret_key_base: 2002f585e9c4ecfd4ae5d4a31ed128eccd6de60d6b13fc95894d97728367c834c00be689188c291f259919e94f4b737100996a7085c6fb5b6ca6904254e8574d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
